### ISSUE TITLE
can be simpler?

### ISSUE THREAD

**Issue by troys-code** [keijiro/UnitySwiftPluginTest#1]
I believe it is possible to make a swift plugin with only 2 files - please correct me if this is not the case.

See https://gist.github.com/troy-lamerton/6499cb8861596281596f2b3604a03359

**Comment by keijiro** [comment]
Yes for simple operations, but my main aim on this project is the groundwork for more complex projects like [StableDiffusionPlugin](https://github.com/keijiro/StableDiffusionPlugin). I needed to use Swift Package Manager to solve dependencies.

**Comment by keijiro** [comment]
I close this issue as answered. Please reopen it for further problems.
